### ISSUE TITLE
Import does not work correctly - getProfileIds isn't able to find the token profile

### ISSUE THREAD

**Issue by EikiEgilz666** [curityio/database-client-migration-example#5]
This part doesn't work:

```
public async getProfileIds(): Promise<string[]> {     
        const profiles = await this.getData('base:profiles/profile/?fields=id;type');
        return profiles['base:profile']
        .filter((profile: any) => profile.type === 'profile-oauth:oauth-service')
        .map((profile: any) => profile.id);
    }
```
    
    it gives the error
    Problem encountered: RESTCONF request to base:profiles/profile/?fields=id;type  failed: Not Found

So I needed to change to this ( hardcoded name of the token service profile ):
```
public async getProfileIds(): Promise<string[]> {        
        return ['token-service'];
        }
```

**Comment by gary-archer** [comment]
We looked into this one and were unable to reproduce it, so I wonder if someone your end could send us a bit more info. In the example, these values are configured in the `.env` file:

```text
ADMIN_BASE_URL=http://localhost:6749
RESTCONF_USER='admin'
RESTCONF_PASSWORD='Password1'
```

Which leads to the following full RESTCONF path, that seems to return a 404 not found error in your setup.

```text
http://localhost:6749/admin/api/restconf/data/base:profiles/profile/?fields=id;type
```

The failed request can be run from a command line tool like this. I wonder if someone your end could run this command, (substituting your own configured values), then send us the output. The data might help us to better understand the cause.

```bash
curl -i -k -v "https://localhost:6749/admin/api/restconf/data/base:profiles/profile/?fields=id;type" \
-u "admin:Password1" \
-H "accept: application/yang-data+json"
```

In a default setup this returns the following JSON data:

```json
{
  "base:profile": [
    {
      "id": "authentication-service",
      "type": "profile-authentication:authentication-service"
    },
    {
      "id": "token-service",
      "type": "profile-oauth:oauth-service"
    }
  ]
}
```

**Comment by EikiEgilz666** [comment]
I've updated to the latest script and run again - maybe this will help your troubleshoot this better @gary-archer  ?

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/3b612828-b856-427c-b6c7-7e7613778dc1)

but it works the moment I change this back (hardcode the name of the token service):

`public async getProfileIds(): Promise<string[]> {
        
        return ['token-service'];
    }`

**Comment by EikiEgilz666** [comment]
This is the path you're trying to navigate to, in the XML:

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/35fe2400-a8a4-482f-8f8b-961a2133d542)

**Comment by gary-archer** [comment]
Hmm - it's a strange one, and seems related to the `type` field in the `fields=id;type` part of the query. As a next step, could you try a few things:

- Re-run the curl command with just `fields=id` and see if that also fails
- Run your development system with a TRACE log level, re-run the failing curl request, then post the logs onto your Slack channel and say it is in response to this issue
- If we need the full configuration we'll get that on the Slack channel also

Regards.

**Comment by gary-archer** [comment]
We've been unable to reproduce this, in various environments, but perhaps changing the query syntax [this pull request](https://github.com/curityio/database-client-migration-example/pull/10) will resolve this for you. Could you try the query there when you get a minute please.

**Comment by gary-archer** [comment]
We resolved this together a while back so closing this issue
