### ISSUE TITLE
When the import has errors - the devops dashboard's database-clients part will break

### ISSUE THREAD

**Issue by EikiEgilz666** [curityio/database-client-migration-example#6]
EDIT: solution in the following post with comments on what can be added for this to make this transition easier

--------

When the import has an error, it will crash the devops dashboards database-clients part

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/d62161da-e714-40c7-883f-63ff4730daae)

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/08df8d74-215a-4799-851e-618e96fd6312)

The database-client part of the devops dashboard can only be restored by deleting the clients that were **successfully** imported in the last run from the database

With this - the database clients in devops dashboard feature will break:
![image](https://github.com/curityio/database-client-migration-example/assets/134059032/07a027b8-fb5f-43fa-9147-9f48c342e97e)

but with this ( only one "test" client created ) it will work again:
![image](https://github.com/curityio/database-client-migration-example/assets/134059032/f4e1121d-2142-4ae8-88f5-b5013f215f1e)

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/8e3a4077-33f8-4703-8ca2-16975c7dbb84)

**Comment by EikiEgilz666** [comment]
nevermind this - now they are duplicate in the config and database, so I'll remove them from the config manually ( in the xml )

please note though:
It would be nice to have a multi-delete in the admin-ui or even remove-from-config-after-import-to-database feature to it would be easier to do the import. Makes no sense having them in the config, after they've been imported to the database

**Comment by gary-archer** [comment]
That one should be the same issue as [issue 8](https://github.com/curityio/database-client-migration-example/issues/8), where the migration stops on the first unexpected error. Note also that the script can be run multiple times without duplicating database clients.

If for some reason a client fails to migrate, there is a workaround you can use, to migrate all other clients. Do so by editing the `environment.ts` file and adding the failed client like this. Hopefully though, the fix of the above issue should mean you don't need to do this.

```javascript
export function isClientToMigrate(id: string): boolean {
    
    if (id === getEnvironmentVariable("MIGRATION_CLIENT_ID") ||
        id == 'devops_dashboard_restconf_client' ||
        id == 'myfailedclient') {

        return false;
    }

    return true;
}
```

The DevOps Dashboard UI error has a separate issue raised with the engineering team. It occurs when the client exists in both the XML configuration and the database. The resolution will be to show a warning against such clients in the DevOps dashboard UI.

**Comment by EikiEgilz666** [comment]
Thanks for the hint but the import works now after your latest update - closing this ticket as well

![image](https://github.com/curityio/database-client-migration-example/assets/134059032/1e62711e-333f-4291-97ff-2bc17321ff4d)
